{
 "title": "LPS  Dashboard Modern",
 "tags": [
  "lps",
  "load-testing",
  "performance"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "plan_name",
    "label": "Plan Name",
    "query": {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_requests\")\r\n  |> keep(columns: [\"plan_name\"])\r\n  |> unique(column: \"plan_name\")"
    }
   },
   {
    "name": "round_name",
    "label": "Round Name",
    "query": {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_requests\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> keep(columns: [\"round_name\"])\r\n  |> unique(column: \"round_name\")"
    }
   },
   {
    "name": "iteration_name",
    "label": "Iteration Name",
    "query": {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_requests\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> keep(columns: [\"iteration_name\"])\r\n  |> unique(column: \"iteration_name\")"
    }
   },
   { "name": "aggregation", "label": "Aggregation", "query": "avg,min,max,p50,p90,p95,p99" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Final status of the iteration",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iteration_final_status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> group()\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Total requests sent during the test",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_requests\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"requests_count\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
    },
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_requests\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"requests_per_second\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "stat",
   "description": "Average response time across all requests",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_duration\")\r\n  |> filter(fn: (r) => r[\"metric\"] == \"total_time\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
    },
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_duration\")\r\n  |> filter(fn: (r) => r[\"metric\"] == \"total_time\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"p99\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Success / Failed",
   "type": "stat",
   "description": "Success vs Failed requests with error rate",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_requests\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"successful_count\" or r[\"_field\"] == \"failed_count\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_field\"])"
    },
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_requests\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"error_rate\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "stat",
   "description": "Total data received with download speed",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_data_transfer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"data_received\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> keep(columns: [\"_value\"])"
    },
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_data_transfer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"downstream_bps\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "description": "Cumulative response code distribution",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_requests\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n\r\n  // Keep ONLY metadata (no fields, no _value)\r\n|> keep(columns: [\r\n  \"_time\",\r\n  \"plan_name\",\r\n  \"round_name\",\r\n  \"iteration_name\",\r\n  \"target\"\r\n])\r\n|> rename(columns: {\r\n  _time: \"Timestamp\",\r\n  plan_name: \"Plan\",\r\n  round_name: \"Round\",\r\n  iteration_name: \"Iteration\",\r\n  target: \"Target URL\"\r\n})\r\n\r\n  // Deterministic row selection\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 1)\r\n\r\n  // Flatten for Grafana\r\n  |> group()\r\n"
    }
   ]
  },
  { "title": "Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Latency Breakdown",
   "type": "table",
   "description": "Cumulative response code distribution",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_duration\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> pivot(\r\n      rowKey: [\"metric\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> keep(columns: [\r\n      \"metric\",\r\n      \"min\",\r\n      \"avg\",\r\n      \"p50\",\r\n      \"p90\",\r\n      \"p95\",\r\n      \"p99\",\r\n      \"max\"\r\n  ])\r\n  |> rename(columns: {\r\n  metric: \"Metric\",\r\n  avg: \"Avg (ms)\",\r\n  min: \"Min (ms)\",\r\n  max: \"Max (ms)\",\r\n  p50: \"P50 (ms)\",\r\n  p90: \"P90 (ms)\",\r\n  p95: \"P95 (ms)\",\r\n  p99: \"P99 (ms)\"\r\n})\r\n\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Requests Summary",
   "type": "table",
   "description": "Cumulative response code distribution",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_requests\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> keep(columns: [\"_field\", \"_value\"])\r\n  |> pivot(\r\n      rowKey: [],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> rename(columns: {\r\n  error_rate: \"Error Rate (%)\",\r\n  failed_count: \"Failed Requests\",\r\n  successful_count: \"Successful Requests\",\r\n  requests_count: \"Total Requests\",\r\n  requests_per_second: \"Requests / Second\",\r\n  requests_rate_per_cooldown: \"Requests / Window\",\r\n  max_concurrent_requests: \"Max Concurrent Requests\"\r\n})\r\n\r\n  |> drop(columns: [\"time_elapsed_ms\"])\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "table",
   "description": "Cumulative response code distribution",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_response_codes\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> group(columns: [\"status_code\", \"status_reason\"])\r\n  |> last()\r\n  |> keep(columns: [\"status_code\", \"status_reason\", \"_value\"])\r\n|> rename(columns: {\r\n    _value: \"Count\",\r\n    status_code: \"HTTP Status\",\r\n    status_reason: \"Reason\"\r\n})\r\n  |> group()   // 🔴 THIS IS THE KEY LINE\r\n"
    }
   ]
  },
  {
   "title": "Data Transfer Summary",
   "type": "table",
   "description": "Cumulative response code distribution",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_data_transfer\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> last()\r\n  |> keep(columns: [\"_field\", \"_value\"])\r\n  |> pivot(\r\n      rowKey: [],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> group()\r\n  |> rename(columns: {\r\n  data_received: \"Total Received\",\r\n  data_sent: \"Total Sent\",\r\n  downstream_bps: \"Avg Received/Sec\",\r\n  upstream_bps: \"Avg Sent/Sec\",\r\n  total_bps: \"Avg Total Sent/Sec\",\r\n  avg_data_received: \"Avg Received/Req (B)\",\r\n  avg_data_sent: \"Avg Sent/Req  (B)\"\r\n\r\n})\r\n"
    }
   ]
  },
  { "title": "Windowed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Requests Count (Per Window)",
   "type": "timeseries",
   "description": "Request counts per cooldown window",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windowed_requests\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Latency Over Time (Windowed)",
   "type": "timeseries",
   "description": "Windowed latency metrics per cooldown period",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windowed_duration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${aggregation}\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> keep(columns: [\"_time\", \"_value\", \"metric\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Response Codes (Per Window)",
   "type": "timeseries",
   "description": "Response codes per cooldown window",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windowed_response_codes\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"status_code\"])"
    }
   ]
  },
  {
   "title": "Data Transfer (Per Window)",
   "type": "timeseries",
   "description": "Data transfer per cooldown window",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"windowed_data_transfer\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  { "title": "Cumulative", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Latency Over Time (Cumulative)",
   "type": "timeseries",
   "description": "Cumulative latency metrics over time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_duration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${aggregation}\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> keep(columns: [\"_time\", \"_value\", \"metric\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Requests Count (Cumulative)",
   "type": "timeseries",
   "description": "Cumulative request counts over time",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_requests\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"max_concurrent_requests\" or r[\"_field\"] == \"requests_per_second\" or r[\"_field\"] == \"requests_rate_per_cooldown\" or r[\"_field\"] == \"error_rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Data Transfer (Cumulative)",
   "type": "timeseries",
   "description": "Cumulative data transfer metrics",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"LPS_Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulative_data_transfer\")\r\n  |> filter(fn: (r) => contains(value: r[\"plan_name\"], set: ${plan_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"round_name\"], set: ${round_name:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"iteration_name\"], set: ${iteration_name:json}))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"downstream_bps\" or r[\"_field\"] == \"total_bps\" or r[\"_field\"] == \"upstream_bps\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  }
 ]
}